version: '3.9'

services:
  character-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: character-api-container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["uvicorn", "app.services.main:app", "--host", "0.0.0.0", "--port", "8000"]