version: '3.9'

services:
  character-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: character-api-container
    ports:
      - "8001:8001"
    volumes:
      - .:/app
      - db-data:/app/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001"]

volumes:
  db-data: